# Generated by Django 4.1.2 on 2022-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("daemon", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IMac",
            new_name="IMacModel",
        ),
    ]
