# Generated by Django 4.1.2 on 2022-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daemon", "0005_remove_imacmodel_alive_imacmodel_cpu_cores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imacmodel",
            name="storage_capacity",
            field=models.FloatField(),
        ),
    ]
