# Generated by Django 4.1.2 on 2022-11-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daemon", "0006_alter_imacmodel_storage_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="imacmodel",
            name="report_status",
            field=models.BooleanField(default=True),
        ),
    ]
